# This is a basic workflow to help you get started with Actions

name: Git Diff

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      URL: https://troy-ci-dev-ed.my.salesforce.com
      USERNAME: troy@ey.com.ci
      CLIENTID: 3MVG9Kip4IKAZQEXB5CUNPvpG6ILY3l2Cil5jny3L442H1nnLMxLBhKcUB.VpDgJq0kTedCR9eA==

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - uses: actions/setup-java@v1
      with:
        java-version: '14.0.2' # The JDK version to make available on the path.
        architecture: x64 # (x64 or x86) - defaults to x64
    
    - name: Execute GitDiff
      run: java -cp java -jar ./buildfiles/GitDiff.jar "TroyBranch"
    
    - name: List Files
      run: ls -R
        
    - name: Install SFDX
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
        
    - name: Authorize Sandbox
      run: sfdx force:auth:jwt:grant --clientid $CLIENTID --jwtkeyfile ./buildfiles/WorldpayDevHub.key --username $USERNAME --instanceurl $URL -a ciSandbox
    
    - name: Execute Delete
      run: sfdx force:source:delete -p "ReleaseDeploy\force-app" -c -u ciSandbox
      
    - name: Execute Deploy
      run: sfdx force:source:deploy -p "ReleaseDeploy\force-app" -c -u ciSandbox
